---
- name: "Install Nginx, PHP on Ububntu 14.04"
  hosts: development
  become: yes
  remote_user: vagrant
  gather_facts: yes

  roles:
    - common
    - firewall
    - nginx
    - php-fpm
    - wordpress